name: Makefile CI

on:
  push:
    paths-exclude:
    - '.github/workflows/cmake.yml'
    - '.gitignore'
    - 'README'
    - '**README'
    - 'LICENSE'
    - 'CMAKE**'
    - '**CMakeLists.txt'
  pull_request:
    paths-exclude:
    - '.github/workflows/cmake.yml'
    - '.gitignore'
    - 'README'
    - '**README'
    - 'LICENSE'
    - 'CMAKE**'
    - '**CMakeLists.txt'

defaults:
  run:
    shell: bash

jobs:

  build-all:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout ScaLAPACK
      uses: actions/checkout@v4

    - name: Setup MPI
      run: |
        sudo apt -y update
        sudo apt -y install openmpi-bin libopenmpi-dev

    - name: Install BLAS and LAPACK
      run: |
        sudo apt -y install libblas-dev liblapack-dev

    - name: Build ScaLAPACK
      run: |
        cp SLmake.inc.example SLmake.inc
        make -j1 -l0.001 FCFLAGS=-fallow-argument-mismatch lib
        make all
        
    - name: Run examples
      working-directory: ${{github.workspace}}/EXAMPLE
      run: |
        mpirun -n 4 ./xsscaex
        mpirun -n 4 ./xdscaex
        mpirun -n 4 ./xcscaex
        mpirun -n 4 ./xzscaex
